Repository saramdle/blog-team-four, pull requests merged in 2023-04, with the labels that each got.

#46 feat : 구글 소셜로그인 구현
  back/blog/.gitignore
  back/blog/build.gradle
  back/blog/src/main/java/saramdle/blog/config/auth/CustomOAuth2UserService.java
  back/blog/src/main/java/saramdle/blog/config/auth/SecurityConfig.java
  back/blog/src/main/java/saramdle/blog/config/auth/SessionConst.java
  back/blog/src/main/java/saramdle/blog/config/auth/dto/OAuthAttributes.java
  back/blog/src/main/java/saramdle/blog/config/auth/dto/SessionUser.java
  back/blog/src/main/java/saramdle/blog/controller/HomeController.java
  back/blog/src/main/java/saramdle/blog/domain/Role.java
  back/blog/src/main/java/saramdle/blog/domain/User.java
  back/blog/src/main/java/saramdle/blog/domain/UserRepository.java
  back/blog/src/main/resources/application.yml
Labels: ♻️ refactor, ✨ feat, 🔬 chore

#45 feat : 댓글 수정 및 삭제 기능
  front/app/posts/[postId]/CommentInput.tsx
  front/app/posts/[postId]/Comments.tsx
  front/app/posts/[postId]/SingleComment.tsx
  front/app/posts/[postId]/page.tsx
  front/db.json
Labels: ✨ feat

#48 refactor : 기존 author 필드를 회원 엔티티로 변경 및 연관관계 적용
  back/blog/src/main/java/saramdle/blog/controller/CommentController.java
  back/blog/src/main/java/saramdle/blog/controller/PostController.java
  back/blog/src/main/java/saramdle/blog/domain/Comment.java
  back/blog/src/main/java/saramdle/blog/domain/CommentRequestDto.java
  back/blog/src/main/java/saramdle/blog/domain/CommentResponseDto.java
  back/blog/src/main/java/saramdle/blog/domain/Post.java
  back/blog/src/main/java/saramdle/blog/domain/PostRequestDto.java
  back/blog/src/main/java/saramdle/blog/domain/PostResponseDto.java
  back/blog/src/main/java/saramdle/blog/service/PostService.java
  back/blog/src/main/resources/application.yml
  back/blog/src/test/java/saramdle/blog/service/CommentServiceTest.java
  back/blog/src/test/java/saramdle/blog/service/PostServiceTest.java
  back/blog/src/test/resources/application.yml
Labels: ♻️ refactor

#51 feat : 댓글 client side rendering으로 전환
  front/app/layout.tsx
  front/app/lib/TanStackWrapper.tsx
  front/app/posts/[postId]/CommentInput.tsx
  front/app/posts/[postId]/Comments.tsx
  front/app/posts/[postId]/SingleComment.tsx
  front/db.json
  front/package-lock.json
  front/package.json
Labels: ✨ feat

#56 feat : 이미지 첨부 기능 구현
  front/app/write/page.tsx
Labels: ✨ feat

#58 feat : footer 컴포넌트 생성 및 적용
  front/app/components/Footer.tsx
  front/app/components/Navbar.tsx
  front/app/globals.css
  front/app/layout.tsx
  front/app/posts/AddFloating.tsx
  front/app/write/page.tsx
Labels: ✨ feat

#59 feat : 시큐리티에서 사용되는 인증된 사용자 객체를 커스터마이징
  back/blog/src/main/java/saramdle/blog/config/auth/CustomOAuth2UserService.java
  back/blog/src/main/java/saramdle/blog/config/auth/CustomUserPrinciple.java
  back/blog/src/main/java/saramdle/blog/config/auth/SessionConst.java
  back/blog/src/main/java/saramdle/blog/config/auth/dto/LoginUser.java
  back/blog/src/main/java/saramdle/blog/controller/HomeController.java
Labels: ♻️ refactor, ✨ feat, 🗑️ remove

#61 feat : 로그인된 사용자 정보로 게시물 및 댓글 API를 처리하는 기능 구현
  back/blog/src/main/java/saramdle/blog/config/auth/CustomUserPrinciple.java
  back/blog/src/main/java/saramdle/blog/config/auth/SecurityConfig.java
  back/blog/src/main/java/saramdle/blog/controller/CommentController.java
  back/blog/src/main/java/saramdle/blog/controller/PostController.java
  back/blog/src/main/java/saramdle/blog/domain/CommentRequestDto.java
  back/blog/src/main/java/saramdle/blog/domain/CommentResponseDto.java
  back/blog/src/main/java/saramdle/blog/domain/PostRequestDto.java
  back/blog/src/main/java/saramdle/blog/domain/PostResponseDto.java
  back/blog/src/main/java/saramdle/blog/service/CommentService.java
  back/blog/src/main/java/saramdle/blog/service/PostService.java
  back/blog/src/main/java/saramdle/blog/service/UserService.java
  back/blog/src/test/java/saramdle/blog/domain/common/BaseTimeEntityTest.java
  back/blog/src/test/java/saramdle/blog/service/CommentServiceTest.java
  back/blog/src/test/java/saramdle/blog/service/PostServiceTest.java
  back/blog/src/test/java/saramdle/blog/service/UserServiceTest.java
Labels: ♻️ refactor, ✨ feat
