Repository saramdle/blog-team-four, pull requests merged in 2023-03, with the labels that each got.

#8 feat : metadata 동적 변화
  front/app/posts/[postId]/page.tsx
  front/db.json
Labels: ♻️ refactor, ✨ feat

#9 feat : 게시물 Create 기능 개발
  back/blog/src/main/java/saramdle/blog/domain/Post.java
  back/blog/src/main/java/saramdle/blog/domain/PostRepository.java
  back/blog/src/main/java/saramdle/blog/service/PostService.java
  back/blog/src/test/java/saramdle/blog/service/PostServiceTest.java
Labels: ✨ feat

#12 feat : 게시물 Read 기능 개발
  back/blog/src/main/java/saramdle/blog/service/PostService.java
  back/blog/src/test/java/saramdle/blog/service/PostServiceTest.java
Labels: ✨ feat

#15 feat : 게시물 Update, Delete 기능 개발
  back/blog/src/main/java/saramdle/blog/domain/Post.java
  back/blog/src/main/java/saramdle/blog/service/PostService.java
  back/blog/src/test/java/saramdle/blog/service/PostServiceTest.java
  back/blog/src/test/resources/application.yml
Labels: ♻️ refactor, ✨ feat, 🔬 chore

#21 feat : 댓글 Update 기능 구현
  back/blog/src/main/java/saramdle/blog/domain/Comment.java
  back/blog/src/main/java/saramdle/blog/service/CommentService.java
  back/blog/src/test/java/saramdle/blog/service/CommentServiceTest.java
Labels: ✨ feat

#26 feat : 댓글 Delete 기능 구현
  back/blog/src/main/java/saramdle/blog/service/CommentService.java
  back/blog/src/test/java/saramdle/blog/service/CommentServiceTest.java
Labels: ✨ feat

#27 feat : 생성, 수정시간을 자동으로 설정해주는 BaseTimeEntity 적용
  back/blog/src/main/java/saramdle/blog/BlogApplication.java
  back/blog/src/main/java/saramdle/blog/domain/Comment.java
  back/blog/src/main/java/saramdle/blog/domain/Post.java
  back/blog/src/main/java/saramdle/blog/domain/common/BaseTimeEntity.java
  back/blog/src/test/java/saramdle/blog/domain/common/BaseTimeEntityTest.java
Labels: ♻️ refactor, ✨ feat

#32 feat : 댓글 컨트롤러 개발
  back/blog/src/main/java/saramdle/blog/controller/CommentController.java
  back/blog/src/main/java/saramdle/blog/domain/CommentRequestDto.java
  back/blog/src/main/java/saramdle/blog/domain/CommentResponseDto.java
Labels: ✨ feat

#36 feat : 댓글 입력창 UI/UX구현
  front/.env
  front/app/posts/[postId]/CommentInput.tsx
  front/app/posts/[postId]/page.tsx
  front/db.json
Labels: ✨ feat

#34 feat : API 예외 처리
  back/blog/src/main/java/saramdle/blog/domain/exception/BusinessException.java
  back/blog/src/main/java/saramdle/blog/domain/exception/ExceptionControllerAdvice.java
  back/blog/src/main/java/saramdle/blog/domain/exception/ExceptionResponse.java
  back/blog/src/main/java/saramdle/blog/domain/exception/NotFoundException.java
  back/blog/src/main/java/saramdle/blog/service/CommentService.java
  back/blog/src/main/java/saramdle/blog/service/PostService.java
  back/blog/src/test/java/saramdle/blog/service/CommentServiceTest.java
  back/blog/src/test/java/saramdle/blog/service/PostServiceTest.java
Labels: ✨ feat

#37 feat : 댓글들을 화면에 보여주는 UI 구현
  front/app/layout.tsx
  front/app/posts/[postId]/CommentInput.tsx
  front/app/posts/[postId]/Comments.tsx
  front/app/posts/[postId]/page.tsx
  front/db.json
  front/package-lock.json
  front/package.json
Labels: ✨ feat
